esphome:
  name: ble
  platform: ESP32
  board: esp-wrover-kit

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Warsaw"

sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:65:4F:C8
    bindkey: 03e3013295e805e78bb4ed014768e6c0
    temperature:
      name: "Xiaomi small Temperature"
    humidity:
      name: "Xiaomi small Humidity"
    battery_level:
      name: "Xiaomi small Battery Level"
  - platform: xiaomi_lywsd02
    mac_address: E7:2E:00:82:DC:48
    temperature:
      name: "Xiaomi small room clock Temperature"
    humidity:
      name: "Xiaomi small room clock Humidity"
  - platform: xiaomi_lywsd02
    mac_address: E7:2E:00:81:74:A1
    temperature:
      name: "Xiaomi bathroom clock Temperature"
    humidity:
      name: "Xiaomi bathroom clock Humidity"


ble_client:
  - mac_address: E7:2E:00:82:DC:48
    id:  lywsd02_small_room
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to lywsd02_small_room!");
        - delay: 20s
        - ble_client.ble_write:
            id: lywsd02_small_room
            service_uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6 
            characteristic_uuid: EBE0CCB7-7A0A-4B0C-8A1A-6FF2997DA3A6
            value: !lambda |-
                auto time = id(sntp_time).now();
                uint8_t time_byte1 =  time.timestamp & 0x000000ff;
                uint8_t time_byte2 = (time.timestamp & 0x0000ff00) >> 8;
                uint8_t time_byte3 = (time.timestamp & 0x00ff0000) >> 16;
                uint8_t time_byte4 = (time.timestamp & 0xff000000) >> 24;
                return {time_byte1, time_byte2, time_byte3, time_byte4};
        - delay: 20s
        - switch.turn_off: lywsd02_ble_connection_small_room
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from lywsd02_small_room!");
  - mac_address: E7:2E:00:81:74:A1
    id:  lywsd02_bathroom
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to lywsd02_bathroom!");
        - delay: 20s
        - ble_client.ble_write:
            id: lywsd02_bathroom
            service_uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6 
            characteristic_uuid: EBE0CCB7-7A0A-4B0C-8A1A-6FF2997DA3A6
            value: !lambda |-
                auto time = id(sntp_time).now();
                uint8_t time_byte1 =  time.timestamp & 0x000000ff;
                uint8_t time_byte2 = (time.timestamp & 0x0000ff00) >> 8;
                uint8_t time_byte3 = (time.timestamp & 0x00ff0000) >> 16;
                uint8_t time_byte4 = (time.timestamp & 0xff000000) >> 24;
                return {time_byte1, time_byte2, time_byte3, time_byte4};
        - delay: 20s
        - switch.turn_off: lywsd02_ble_connection_bathroom
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from lywsd02_bathroom!");

switch:
  - platform: ble_client
    ble_client_id: lywsd02_small_room
    id: "lywsd02_ble_connection_small_room"
  - platform: ble_client
    ble_client_id: lywsd02_bathroom
    id: "lywsd02_ble_connection_bathroom"
    

interval:
  - interval: 7d
    then:
      - switch.turn_on: lywsd02_ble_connection_small_room
      - switch.turn_on: lywsd02_ble_connection_bathroom